import Footer from "./_components/Footer";
import Header from "./_components/header/Header";
import "./globals.css";

export const metadata = {
  title: "Bright-mind",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Header />
        <main className="">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
